# Generated by Django 3.1.7 on 2021-03-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='model',
            field=models.CharField(blank=True, db_column='model', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='osVersion',
            field=models.CharField(blank=True, db_column='os_version', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='phoneNumber',
            field=models.CharField(blank=True, db_column='phone_number', default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='platform',
            field=models.CharField(blank=True, db_column='platform', default=None, max_length=25, null=True),
        ),
    ]
