# Generated by Django 3.1.7 on 2021-03-12 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_auto_20210312_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='model',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='osVersion',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='platform',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=255),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='otpVerified',
            field=models.BooleanField(db_column='otp_verified', default=False),
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, db_column='platform', default=None, max_length=25, null=True)),
                ('model', models.CharField(blank=True, db_column='model', default=None, max_length=100, null=True)),
                ('osVersion', models.CharField(blank=True, db_column='os_version', default=None, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now=True, db_column='created')),
                ('updated', models.DateTimeField(auto_now_add=True, db_column='updated')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_rel_cad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Users Details',
                'db_table': 'USER_DETAILS',
                'ordering': ('created',),
            },
        ),
    ]
