# Generated by Django 3.1.7 on 2021-03-12 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_auto_20210312_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='name',
            field=models.CharField(db_column='name', max_length=255),
        ),
        migrations.CreateModel(
            name='EmailDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, db_column='created')),
                ('isActive', models.BooleanField(db_column='is_active', default=True)),
                ('type', models.CharField(choices=[('1', 'Registration'), ('2', 'Resend'), ('3', 'ForgotPassword')], db_column='email_type', default=None, max_length=25)),
                ('otpCode', models.CharField(db_column='otp_code', max_length=4)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_rel_ced', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customers Email Directory',
                'db_table': 'EMAIL_DIRECTORY',
            },
        ),
    ]
