# Generated by Django 3.1.7 on 2021-03-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0005_auto_20210312_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDeviceDetails',
        ),
        migrations.AlterModelOptions(
            name='userdevicedetails',
            options={'ordering': ('created',), 'verbose_name': 'Users Device Details'},
        ),
        migrations.AlterField(
            model_name='emaildirectory',
            name='type',
            field=models.CharField(choices=[('Registration', 'Registration'), ('Resend', 'Resend'), ('ForgotPassword', 'ForgotPassword')], db_column='email_type', default=None, max_length=25),
        ),
        migrations.AlterModelTable(
            name='userdevicedetails',
            table='USER_DEVICE_DETAILS',
        ),
    ]
