# Generated by Django 3.1.7 on 2021-03-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0007_auto_20210312_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(db_column='cat_name', max_length=1000)),
                ('catDescription', models.CharField(db_column='cat_description', max_length=5000)),
                ('telName', models.CharField(db_column='tel_name', max_length=1000)),
                ('telPdfUrl', models.CharField(db_column='tel_pdf_url', max_length=5000)),
                ('hindiName', models.CharField(db_column='hindi_name', max_length=1000)),
                ('hindiPdfUrl', models.CharField(db_column='hindi_pdf_url', max_length=5000)),
            ],
        ),
    ]
