# Generated by Django 3.1.7 on 2021-03-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0009_auto_20210313_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categories'},
        ),
        migrations.AlterModelTable(
            name='categories',
            table='CATEGORIES',
        ),
    ]
