# Generated by Django 3.1.7 on 2021-03-13 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0011_auto_20210313_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='catDescription',
            field=models.TextField(db_column='cat_description', max_length=5000, verbose_name='English Description'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='catName',
            field=models.CharField(db_column='cat_name', max_length=1000, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='hindiName',
            field=models.CharField(db_column='hindi_name', max_length=1000, verbose_name='Hindi Name'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='hindiPdfUrl',
            field=models.TextField(db_column='hindi_pdf_url', max_length=5000, verbose_name='Hindi Description'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='isActive',
            field=models.BooleanField(db_column='is_active', default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='telName',
            field=models.CharField(db_column='tel_name', max_length=1000, verbose_name='Telugu Name'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='telPdfUrl',
            field=models.TextField(db_column='tel_pdf_url', max_length=5000, verbose_name='Telugu Description'),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255, verbose_name='Name')),
                ('phoneNumber', models.CharField(blank=True, db_column='phone_number', default=None, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.CharField(blank=True, db_column='email_id', default=None, max_length=150, null=True, verbose_name='Email Id')),
                ('type', models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Completed', 'Completed')], db_column='email_type', default=None, max_length=25)),
                ('description', models.TextField(db_column='description', max_length=5000, verbose_name='Description')),
                ('reply', models.TextField(db_column='reply', max_length=5000, verbose_name='Reply')),
                ('locationType', models.CharField(blank=True, db_column='location_type', default=None, max_length=25, null=True, verbose_name='Location Type')),
                ('address', models.CharField(blank=True, db_column='address', default=None, max_length=150, null=True)),
                ('city', models.CharField(blank=True, db_column='city', default=None, max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_column='state', default=None, max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_column='country', default=None, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, db_column='zip', default=None, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now=True, db_column='created')),
                ('updated', models.DateTimeField(auto_now_add=True, db_column='updated')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='service_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
