# Generated by Django 3.1.7 on 2021-03-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0012_auto_20210313_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'verbose_name': 'Service Request', 'verbose_name_plural': 'Service Requests'},
        ),
        migrations.AlterModelTable(
            name='servicerequest',
            table='SERVICE_REQUEST',
        ),
    ]
