# Generated by Django 3.1.7 on 2021-03-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0013_auto_20210313_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='locationType',
            field=models.CharField(choices=[('auto', 'auto'), ('manual', 'manual')], db_column='location_type', max_length=25, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='type',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Completed', 'Completed')], db_column='email_type', max_length=25),
        ),
    ]
