# Generated by Django 3.1.7 on 2021-03-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0014_auto_20210313_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='type',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='message',
            field=models.TextField(db_column='message', default='message', max_length=5000, verbose_name='Message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Completed', 'Completed')], db_column='status', default='Open', max_length=25),
            preserve_default=False,
        ),
    ]
