# Generated by Django 3.1.7 on 2021-03-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0015_auto_20210313_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='email',
            field=models.CharField(db_column='email_id', default='test@tet.com', max_length=150, verbose_name='Email Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='reply',
            field=models.TextField(blank=True, db_column='reply', max_length=5000, null=True, verbose_name='Reply'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Completed', 'Completed')], db_column='status', default='Pending', max_length=25),
        ),
    ]
